#!/bin/sh
# bootstrap environment for ubuntu 14.04 live usb 

##########################################
# system setup part

LIVE_USER=$USER
export LIVE_USER

sudo -H sh -c "

# user binary path
if [ -d /media/ubuntu/casper-rw ]
then
  sudo -H mkdir -p /media/ubuntu/casper-rw/data
  sudo -H chown $LIVE_USER:$LIVE_USER /media/ubuntu/casper-rw/data
  mkdir -p /media/ubuntu/casper-rw/cache
  OPT_CACHE_DIR=-o=Dir::Cache::Archives=/media/ubuntu/casper-rw/cache
fi

# enable universe repository apt get update, install extra packages
add-apt-repository universe && 
apt-get -y update && 
apt-get -y \$OPT_CACHE_DIR install vim exuberant-ctags git sshfs docker.io

# fix locale
locale-gen ko-KR.UTF-8
update-locale

" # end of sudo -H sh -c

##########################################
# user setup part


# user binary path
if [ -d /media/ubuntu/casper-rw/data ]
then
  HOME_LOCAL=/media/ubuntu/casper-rw/data/.local
else
  HOME_LOCAL=$HOME/.local
fi

mkdir -p $HOME_LOCAL
export HOME_LOCAL

# update .bashrc
case :$PATH: in
*:$HOME_LOCAL/bin:*)
  ;;
*)
  cat <<EEE >> ~/.bashrc
export PATH=$HOME_LOCAL/bin:$PATH

# sshfs
sshfs(){
    \sshfs "$@" -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3
}

# google-chrome installer
install_google_chrome(){(
  test -f $HOME_LOCAL/cache/linux_signing_key.pub || \
    wget -q https://dl-ssl.google.com/linux/linux_signing_key.pub -O $HOME_LOCAL/cache/linux_signing_key.pub
  sudo -H apt-key add $HOME_LOCAL/cache/linux_signing_key.pub
  test -f /etc/apt/source.list.d/google-chrome.list || \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo -H tee -a /etc/apt/sources.list.d/google-chrome.list
  which google-chrome >/dev/null 2>&1 || \
    sudo -H apt-get -o=Dir::Cache::Archives=/media/ubuntu/casper-rw/cache install google-chrome
)}

# microsoft-vscode installer
install_code(){(
  test -f $HOME_LOCAL/cache/vscode.deb || \
    wget "https://go.microsoft.com/fwlink/?LinkID=760868" -O $HOME_LOCAL/cache/vscode.deb
  which code >/dev/null 2>&1 || \
    sudo -H dpkg -i $HOME_LOCAL/cache/vscode.deb
)}

# node-js installer ( via node-manager )
install_npm(){(
  if [ -d /media/ubuntu/casper-rw/data/.local ]
  then
    HOME_LOCAL=/media/ubuntu/casper-rw/data/.local
  else
    HOME_LOCAL=$HOME/.local
  fi
  test -d $HOME_LOCAL/cache/n || \
    git clone https://github.com/rhee/n.git $HOME_LOCAL/cache/n
  which npm >/dev/null 2>&1 || \
    ( cd $HOME_LOCAL/cache/n && make PREFIX=$HOME_LOCAL install; $PREFIX/bin/n lts )
)}

alias i='. ~/.ishrc'
alias kor='export LANG=ko_KR.UTF-8'
EEE
  ;;
esac


# apply to this shell
PATH=$HOME_LOCAL/bin:$PATH


# install default .rcfiles
test -d $HOME_LOCAL/cache/_ishrc || git clone https://github.com/rhee/_ishrc.git $HOME_LOCAL/cache/_ishrc
test -f ~/.ishrc || (cd $HOME_LOCAL/cache/_ishrc; sh install.sh; rm -fv ~/.gitconfig; mv ~/.gitconfig- ~/.gitconfig)


#############

git config --global user.email "shr386+github@hotmail.com"
git config --global user.name "Sang-Hoon RHEE"

##########################################
# console/terminal setup part

# disable touchpad
synclient TouchpadOff=1

# remap key capslock as control
setxkbmap -layout us -option ctrl:nocaps
